apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
  - ../../base
images:
  - name: PLACEHOLDER_IMAGE
    newName: docker.io/archcra/st31
    newTag: st31-developer-73
commonLabels:
  env: dev
